# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Taralizer < Formula
  desc "Taralizer is a Threat and Risk Analysis tool using the extendable OPA rules engine to implement the OWASP ASVS standard."
  homepage "https://github.com/devmatic-it/taralizer"
  version "0.1.10"
  license "Apache 2.0"

  depends_on "graphviz" => :mandatory
  depends_on "wkhtmltopdf" => :mandatory

  on_macos do
    if Hardware::CPU.arm?
      url " https://github.com/devmatic-it/taralizer/releases/v0.1.10/taralizer_0.1.10_darwin_arm64.zip"
      sha256 "bd4b1f21aaa6243f39417aa34c84322c9330625f430cc70f14cb772e1478d83c"

      def install
        bin.install "taralizer"
      end
    end
    if Hardware::CPU.intel?
      url " https://github.com/devmatic-it/taralizer/releases/v0.1.10/taralizer_0.1.10_darwin_amd64.zip"
      sha256 "ae8fd719b6320c19c696fd4a2b0d38776785f22731357f5d927a772c5a389720"

      def install
        bin.install "taralizer"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url " https://github.com/devmatic-it/taralizer/releases/v0.1.10/taralizer_0.1.10_linux_amd64.zip"
      sha256 "aff14cef4ef8cdcbe3b917519ea5b0a5553d7399309f4195c7503406df9222bf"

      def install
        bin.install "taralizer"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url " https://github.com/devmatic-it/taralizer/releases/v0.1.10/taralizer_0.1.10_linux_arm64.zip"
      sha256 "4e4eeabbd14c2e8bc324b01207791711969b0d57a8c55b8d72016c2d4bde6879"

      def install
        bin.install "taralizer"
      end
    end
  end

  test do
    system "#{bin}/taralizer version"
  end
end
