// Package taralizer Threat and Risk Analyzer
// Copyright 2021 taralizer authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
package taralizer

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestNewReporting(t *testing.T) {
	report, err := Load("../../examples/gcp/bank_of_anthos.yaml")
	if err != nil {
		t.Fatalf("Failed to load model: %v", err)
	}
	engine := NewReportEngine()
	if err := engine.GenerateReport(os.Stdout, "../../templates/html.tpl", report); err != nil {
		t.Fatalf("GenerateReport failed: %v", err)
	}
}

func TestGenerateReportFilePDFChromedp(t *testing.T) {
	report, err := Load("../../examples/gcp/bank_of_anthos.yaml")
	if err != nil {
		t.Fatalf("Failed to load model: %v", err)
	}

	engine := NewReportEngine()
	tmpDir := t.TempDir()
	outputPath := filepath.Join(tmpDir, "test_report.pdf")

	err = engine.GenerateReportFilePDF(outputPath,
		"../../templates/pdf_report.tpl",
		"../../templates/pdf_report_cover.tpl", report)
	if err != nil {
		t.Fatalf("Failed to generate PDF: %v", err)
	}

	info, err := os.Stat(outputPath)
	if err != nil {
		t.Fatalf("PDF file not found: %v", err)
	}
	if info.Size() == 0 {
		t.Fatal("Generated PDF is empty")
	}
	t.Logf("Generated PDF: %d bytes", info.Size())
}

func TestGenerateConsoleReport(t *testing.T) {
	report := Report{
		Title:    "Test Report",
		Customer: "Test Customer",
		Date:     "2024-01-01",
		Author: Author{
			Name: "Test Author",
		},
		Risks: []Risk{
			{
				Id:         "test-risk-1",
				Title:      "Test Risk",
				Message:    "This is a test risk",
				Likelihood: 2,
				Impact:     3,
				Severity:   6,
				Cwe:        79,
				Url:        "https://cwe.mitre.org/data/definitions/79",
			},
		},
	}

	engine := NewReportEngine()
	tplDir := "../../templates/"

	// Write to a temp file to verify output
	tmpDir := t.TempDir()
	outputPath := tmpDir + "console_output.md"
	fo, err := os.Create(outputPath)
	if err != nil {
		t.Fatalf("create output file: %v", err)
	}

	err = engine.GenerateReport(fo, tplDir+"console.tpl", report)
	fo.Close()
	if err != nil {
		t.Fatalf("GenerateReport failed: %v", err)
	}

	// Read and verify output
	output, err := os.ReadFile(outputPath)
	if err != nil {
		t.Fatalf("read output: %v", err)
	}
	outputStr := string(output)

	// Verify output contains expected markdown
	if !strings.Contains(outputStr, "# Risk Assessment Report") {
		t.Error("Output missing main heading")
	}
	if !strings.Contains(outputStr, "## Test Report") {
		t.Error("Output missing report title")
	}
	if !strings.Contains(outputStr, "**Customer:** Test Customer") {
		t.Error("Output missing customer info")
	}
	if !strings.Contains(outputStr, "## Identified Risks") {
		t.Error("Output missing risks section")
	}
	if !strings.Contains(outputStr, "test-risk-1") {
		t.Error("Output missing risk ID")
	}
	if !strings.Contains(outputStr, "Test Risk") {
		t.Error("Output missing risk title")
	}
	if !strings.Contains(outputStr, "MED") {
		t.Error("Output missing likelihood label")
	}
	if !strings.Contains(outputStr, "HIGH") {
		t.Error("Output missing impact label")
	}
	if !strings.Contains(outputStr, "CWE-79") {
		t.Error("Output missing CWE reference")
	}
	if !strings.Contains(outputStr, "Report generated by Taralizer") {
		t.Error("Output missing footer")
	}
}

func TestGenerateReportFileMarkdown(t *testing.T) {
	report, err := Load("../../examples/gcp/bank_of_anthos.yaml")
	if err != nil {
		t.Fatalf("Failed to load model: %v", err)
	}

	engine := NewReportEngine()
	tmpDir := t.TempDir()
	outputPath := filepath.Join(tmpDir, "test_report.md")

	err = engine.GenerateReportFileMarkdown(outputPath,
		"../../templates/markdown_report.tpl", report)
	if err != nil {
		t.Fatalf("Failed to generate markdown: %v", err)
	}

	// Verify file exists and is non-empty
	info, err := os.Stat(outputPath)
	if err != nil {
		t.Fatalf("Markdown file not found: %v", err)
	}
	if info.Size() == 0 {
		t.Fatal("Generated markdown is empty")
	}
	t.Logf("Generated markdown: %d bytes", info.Size())

	// Verify content contains expected sections
	content, err := os.ReadFile(outputPath)
	if err != nil {
		t.Fatalf("Failed to read generated markdown: %v", err)
	}
	text := string(content)

	// Check for mermaid block
	if !strings.Contains(text, "```mermaid") {
		t.Error("Generated markdown does not contain a mermaid code block")
	}

	// Check for key sections
	expectedSections := []string{
		"# Threat and Risk Analysis",
		"## Trust Boundaries",
		"## Technical Assets",
		"## Data Assets",
		"## Threat Agents",
		"## Risk Assessment",
		"## Methodology",
		"## About Taralizer",
	}
	for _, section := range expectedSections {
		if !strings.Contains(text, section) {
			t.Errorf("Generated markdown missing section: %s", section)
		}
	}
}
