# Risk Assessment Report

{{if .Title}}## {{.Title}}{{end}}
{{if .Customer}}**Customer:** {{.Customer}}{{end}}
{{if .Date}}**Date:** {{.Date}}{{end}}
{{if .Author.Name}}**Author:** {{.Author.Name}}{{end}}

---

## Identified Risks

| ID | Likelihood | Impact | Severity | Risk |
|----|------------|--------|----------|------|
{{range $risk := .Risks}}| {{$risk.Id}} | {{likelihood $risk.Likelihood}} | {{impact $risk.Impact}} | {{severity $risk.Severity}} | {{if $risk.Url}}[CWE-{{$risk.Cwe}}]({{$risk.Url}}) {{end}}**{{$risk.Title}}**: {{$risk.Message}} |---|
{{end}}

---

Report generated by Taralizer


