# Risk Assessment Report

{{if .Title}}## {{.Title}}{{end}}
{{if .Customer}}**Customer:** {{.Customer}}{{end}}
{{if .Date}}**Date:** {{.Date}}{{end}}
{{if .Author.Name}}**Author:** {{.Author.Name}}{{end}}

---

## Identified Risks

| ID | Likelihood | Impact | Severity | Risk |
|----|------------|--------|----------|------|
{{range $risk := .Risks}}| {{$risk.Id}} | {{likelihood $risk.Likelihood}} | {{impact $risk.Impact}} | {{severity $risk.Severity}} | {{if gt $risk.Cwe 0}}[CWE-{{$risk.Cwe}}](https://cwe.mitre.org/data/definitions/{{$risk.Cwe}}) {{end}}**{{$risk.Title}}**: {{$risk.Message}} |---|
{{end}}

---

Report generated by Taralizer


